version: '3.1'

services:

  frontend:
    container_name: bike-copilot-frontend
    build:
      context: ./bike-copilot-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3020:3000"
