name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  push-tag:
    name: Push Tag
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.bump-version-and-push-tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - id: bump-version-and-push-tag
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0 
        env:
          WITH_V: false
          PRERELEASE: false
  create-release:
    name: Create Release
    needs: push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ jobs.push-tag.outputs.tag }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: false
          prerelease: false
  build-and-push-image:
    name: Build and Push Image
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./frontend/Dockerfile
            image: ghcr.io/${{ github.repository }}-frontend
            context: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

